### ISSUE TITLE
Predict tiles artefact

### ISSUE THREAD

**Issue by ocourtin** [datapink/robosat.pink#59]
Removing overlap with prediction looks like a good idea (~x3 speed improvment and far cleaner code).
But we've got some artefact (time to time) like this:

![Screenshot from 2019-04-12 16-38-12](https://user-images.githubusercontent.com/1718264/56045366-69c0a100-5d41-11e9-82ef-aee92777435b.png)

Looks either if we can reduce the occurence (by DataAugmentation for instance)
or if we can detect it post prediction, to remove it in a second pass (but inside `rsp predict`)

**Comment by Ashargin** [comment]
An idea for solving this problem may be to predict not only the tiles (black) during prediction, but also the tiles at the centers (red), then combine the predictions with the union of the two masks.

This will double the inference time, but this kind of artifacts may disappear because there will be no more edges.

![issue](https://user-images.githubusercontent.com/25967564/66715820-26b2b980-edc8-11e9-88cc-1e5d945e80b6.png)

**Comment by ocourtin** [comment]
@Ashargin  Thanks again for this idea.

A first implementation help indeed to reduce side effect behaviour.
I just add margins notion to your initial suggestion.


To finalize it:
 - [ ] Margin size not hardcoded
 - [ ] CLI ergonomy (i.e not that happy with --translate keyword, and calling `rsp predict` twice)
 - [ ] Update RoboSat.pink extension tutorial

**Comment by ocourtin** [comment]
For the record performances impact on predict time is about x3
