### ISSUE TITLE
Cover tool get wrong result

### ISSUE THREAD

**Issue by wucangeo** [datapink/robosat.pink#73]
use `cover` tool with `bbox = '118.877728,25.3992725, 118.877613,25.3994113' `, and I got the wrong result, which covered 262,145 tiles.
Actually, the bbox covered only one tile.

the wrong result looks like this:

> 0,111939,18
> 1,111939,18
> 2,111939,18
> 3,111939,18
> 4,111939,18
> ...
> 262141,111939,18
> 262142,111939,18
> 262143,111939,18

**Comment by ocourtin** [comment]
Hi @wucangeo,

The bbox you provided as an example is not valid.
It should be: xmin,ymin,xmax,ymax format

This one should be OK:
`rsp cover --bbox 118.877613,25.3992725,118.877728,25.3994113 --zoom 17 cover`

And now since b4b102b this other bbox return an error message rather than an invalid cover:
`rsp cover --bbox 118.877728,25.3992725,118.877613,25.3994113 --zoom 17 cover`

Thanks for this report !


This should close this issue, thanks in advance to test it, and to report any further issue...

**Comment by wucangeo** [comment]
@ocourtin thanks! I will update and test it.
