### ISSUE TITLE
Multi GPU Training

### ISSUE THREAD

**Issue by Roosh27** [datapink/robosat.pink#86]
How do I enable Multi GPU's for Robosat.pink training? The rsp info shows me 2 GPU's, however rsp train is taking a single GPU.

**Comment by ocourtin** [comment]
By default `rsp train` use all GPUs available.
except if envar `CUDA_VISIBLE_DEVICES` is set to restrict on fewer GPU among thoses available.

If `rsp info` show 2 GPUs, `rsp train` is supposed to use theses two.
(as since you launch both commands in the same terminal to be sure that env vars are the same)

HTH,

**Comment by Roosh27** [comment]
Thank you. It is taking two gpus now.
